ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'PARTIAL_FAILED';
ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'FAILED_TEMPLATE';
ALTER TYPE "NotificationStatus" ADD VALUE IF NOT EXISTS 'FAILED_PROVIDER';

ALTER TYPE "NotificationDeliveryStatus" ADD VALUE IF NOT EXISTS 'SKIPPED';
ALTER TYPE "NotificationDeliveryStatus" ADD VALUE IF NOT EXISTS 'PREFERENCE_DISABLED';
